databases:
  - name: micronaut
    databaseName: micronaut_hgo7
    user: micronaut_hgo7_user

services:
  - type: web
    name: pandorasbudget
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: micronaut_hgo7
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false